evecomments/sites/models.py
from evecomments.extensions import db

# Need to import for the foreign key to be detected properly by migration scripts
from evecomments.user.models import UserModel


class SiteModel(db.Model):
    """ Model for individual sites to be placed in the sites table. """

    __tablename__ = 'sites'

    id       = db.Column(db.String(50), primary_key=True)
    name     = db.Column(db.String(50))

    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    owner    = db.relationship('UserModel', backref=db.backref('sites', lazy='dynamic'))

    def __init__(self, site_id, name, owner):
        self.id    = site_id
        self.name  = name
        self.owner = owner

    def __repr__(self):
        return '<SiteModel %s>' % self.id

evecomments/sites/forms.py
from flask_wtf          import Form
from wtforms            import StringField
from wtforms.validators import DataRequired, InputRequired, Length

from evecomments.validators.site import unique_site_id


class AddSiteForm(Form):
    """ Form for adding new sites to the comments system. """

    id   = StringField('Unique ID', validators=[DataRequired(), InputRequired(), Length(min=3, max=50), unique_site_id])
    name = StringField('Site Name', validators=[DataRequired(), InputRequired(), Length(min=3, max=50)])


class EditSiteForm(Form):
    """ Form for editing existing sites. This is done as a new form to help ensure we don't accidentally
     accept an update to the id field. """

    name = StringField('Site Name', validators=[DataRequired(), InputRequired(), Length(min=3, max=50)])

evecomments/sites/views.py
from flask           import Blueprint, render_template, abort
from flask.ext.login import login_required, current_user

from evecomments.extensions    import db
from evecomments.sites.forms   import AddSiteForm, EditSiteForm
from evecomments.sites.models  import SiteModel
from evecomments.threads.forms import EditThreadForm

blueprint = Blueprint('sites', __name__, static_folder='../static')


@blueprint.route('/sites/', methods=('GET', 'POST'))
@login_required
def all_sites():
    add_site_form = AddSiteForm()

    if add_site_form.validate_on_submit():

        new_site = SiteModel(add_site_form.id.data, add_site_form.name.data, current_user)

        db.session.add(new_site)
        db.session.commit()

    sites = SiteModel.query.filter_by(owner=current_user).all()

    template_values = {
        'sites'         : sites,
        'add_site_form' : add_site_form,
    }

    return render_template('sites/all_sites.html', template_values=template_values)


@blueprint.route('/sites/<string:site_id>/details/', methods=('GET', 'POST'))
@login_required
def site_details(site_id):
    site = SiteModel.query.filter_by(id=site_id, owner=current_user).first()

    if site is None:
        abort(404)

    edit_site_form = EditSiteForm()

    if edit_site_form.validate_on_submit():
        site.name = edit_site_form.name.data

        db.session.commit()

    template_values = {
        'site'           : site,
        'edit_site_form' : edit_site_form,
    }

    return render_template('sites/site_details.html', template_values=template_values)


@blueprint.route('/sites/<string:site_id>/comments/', methods=('GET', ))
@login_required
def site_comments(site_id):
    site = SiteModel.query.filter_by(id=site_id, owner=current_user).first()

    if site is None:
        abort(404)

    template_values = {
        'site' : site,
    }

    return render_template('sites/site_comments.html', template_values=template_values)


@blueprint.route('/sites/<string:site_id>/threads/', methods=('GET', ))
@login_required
def site_threads(site_id):
    site = SiteModel.query.filter_by(id=site_id, owner=current_user).first()

    if site is None:
        abort(404)

    edit_thread_form = EditThreadForm()

    template_values = {
        'site'              : site,
        'edit_thread_form' : edit_thread_form,
    }

    return render_template('sites/site_threads.html', template_values=template_values)

evecomments/templates/sites/all_sites.html
{% extends "base_with_nav.html" %}
{% block content %}
    {% if template_values.add_site_form.errors %}
        <ul class="errors">
            {% for field_name, field_errors in template_values.add_site_form.errors|dictsort if field_errors %}
                {% for error in field_errors %}
                    <li>{{ template_values.add_site_form[field_name].label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Sites</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-8">
                            <p>Here is a listing of sites that already exist.
                            You can edit, delete, or view details.</p>
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#add_site">
                                Add New Site
                            </button>
                        </div>
                    </div>
                </div>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in template_values.sites %}
                            <tr>
                                <td>{{ entry.id }}</td>
                                <td>
                                    <a href="{{ url_for('sites.site_details', site_id=entry.id) }}">
                                        {{ entry.name }}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div>
        <div class="modal fade" id="add_site" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Add New Site</h4>
                    </div>
                    <div class="modal-body">
                        <form method="POST" class="form-horizontal" role="form" action="{{ url_for('sites.all_sites') }}">
                            {{ template_values.add_site_form.hidden_tag() }}

                            <div class="form-group">
                                <label for="{{ template_values.add_site_form.id.id }}" class="control-label col-sm-2">{{ template_values.add_site_form.id.label }}</label>
                                <div class="col-sm-10">
                                    {{ template_values.add_site_form.id(size=30, class="form-control", placeholder="Unique ID for the site.") }}
                                </div>

                                <label for="{{ template_values.add_site_form.name.id }}" class="control-label col-sm-2">{{ template_values.add_site_form.name.label }}</label>
                                <div class="col-sm-10">
                                    {{ template_values.add_site_form.name(size=30, class="form-control", placeholder="Name of the new site.") }}
                                </div>
                            </div>

                            <input type="submit" class="btn btn-primary" value="Add New Site">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

evecomments/templates/sites/site_comments.html
{% extends "base_with_nav.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li><a href="{{ url_for('sites.site_details', site_id=template_values.site.id) }}">Details</a></li>
                <li class="active"><a href="{{ url_for('sites.site_comments', site_id=template_values.site.id) }}">Comments</a></li>
                <li><a href="{{ url_for('sites.site_threads', site_id=template_values.site.id) }}">Threads</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                {% for comment in template_values.site.comments %}
                    {{ macros.add_comment(comment) }}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

evecomments/templates/sites/site_details.html
{% extends "base_with_nav.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="{{ url_for('sites.site_details', site_id=template_values.site.id) }}">Details</a></li>
                <li><a href="{{ url_for('sites.site_comments', site_id=template_values.site.id) }}">Comments</a></li>
                <li><a href="{{ url_for('sites.site_threads', site_id=template_values.site.id) }}">Threads</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <form method="POST" class="form-horizontal" role="form" action="{{ url_for('sites.site_details', site_id=template_values.site.id) }}">
                    {{ template_values.edit_site_form.hidden_tag() }}

                    <div class="form-group">
                        <label class="control-label col-sm-2">Site ID: </label>
                        <p class="col-sm-5">{{ template_values.site.id }}</p>
                    </div>

                    <div class="form-group">
                        <label for="{{ template_values.edit_site_form.name.id }}" class="control-label col-sm-2">{{ template_values.edit_site_form.name.label }}</label>
                        <div class="col-sm-10">
                            {{ template_values.edit_site_form.name(size=30, class="form-control", placeholder=template_values.site.name) }}
                        </div>
                    </div>

                    <input type="submit" class="btn btn-primary" value="Save Changes">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

evecomments/templates/sites/site_threads.html
{% extends "base_with_nav.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked">
                <li><a href="{{ url_for('sites.site_details', site_id=template_values.site.id) }}">Details</a></li>
                <li><a href="{{ url_for('sites.site_comments', site_id=template_values.site.id) }}">Comments</a></li>
                <li class="active"><a href="{{ url_for('sites.site_threads', site_id=template_values.site.id) }}">Threads</a></li>
            </ul>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <table class="table">
                    <tr>
                        <th>ID</th>
                        <th>URL</th>
                        <th>Title</th>
                        <th>Created On</th>
                    </tr>
                    {% for thread in template_values.site.threads %}
                        <tr>
                            <td>{{ thread.id }}</td>
                            <td>{{ thread.url }}</td>
                            <td>{{ thread.title }}</td>
                            <td>{{ thread.created_on }}</td>
                            <td>
                                <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#edit_thread">
                                    Edit
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <div>
        <div class="modal fade" id="edit_thread" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Edit Thread</h4>
                    </div>
                    <div class="modal-body">
                        <form method="POST" class="form-horizontal" role="form" action="{{ url_for('sites.site_threads', site_id=template_values.site.id) }}">
                            {{ template_values.edit_thread_form.hidden_tag() }}

                            <input type="submit" class="btn btn-primary" value="Edit Thread">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}