evecomments/sites/views.py
from flask           import Blueprint, render_template, abort
from flask.ext.login import login_required, current_user

from evecomments.extensions    import db
from evecomments.sites.forms   import AddSiteForm, EditSiteForm
from evecomments.sites.models  import SiteModel
from evecomments.threads.forms import EditThreadForm

blueprint = Blueprint('sites', __name__, static_folder='../static')


@blueprint.route('/sites/', methods=('GET', 'POST'))
@login_required
def all_sites():
    add_site_form = AddSiteForm()

    if add_site_form.validate_on_submit():

        new_site = SiteModel(add_site_form.id.data, add_site_form.name.data, current_user)

        db.session.add(new_site)
        db.session.commit()

    sites = SiteModel.query.filter_by(owner=current_user).all()

    template_values = {
        'sites'         : sites,
        'add_site_form' : add_site_form,
    }

    return render_template('sites/all_sites.html', template_values=template_values)


@blueprint.route('/sites/<string:site_id>/details/', methods=('GET', 'POST'))
@login_required
def site_details(site_id):
    site = SiteModel.query.filter_by(id=site_id, owner=current_user).first()

    if site is None:
        abort(404)

    edit_site_form = EditSiteForm()

    if edit_site_form.validate_on_submit():
        site.name = edit_site_form.name.data

        db.session.commit()

    template_values = {
        'site'           : site,
        'edit_site_form' : edit_site_form,
    }

    return render_template('sites/site_details.html', template_values=template_values)


@blueprint.route('/sites/<string:site_id>/comments/', methods=('GET', ))
@login_required
def site_comments(site_id):
    site = SiteModel.query.filter_by(id=site_id, owner=current_user).first()

    if site is None:
        abort(404)

    template_values = {
        'site' : site,
    }

    return render_template('sites/site_comments.html', template_values=template_values)


@blueprint.route('/sites/<string:site_id>/threads/', methods=('GET', ))
@login_required
def site_threads(site_id):
    site = SiteModel.query.filter_by(id=site_id, owner=current_user).first()

    if site is None:
        abort(404)

    edit_thread_form = EditThreadForm()

    template_values = {
        'site'              : site,
        'edit_thread_form' : edit_thread_form,
    }

    return render_template('sites/site_threads.html', template_values=template_values)

evecomments/user/views.py
from datetime import datetime

from flask           import Blueprint, request, session, redirect, url_for, render_template
from flask.ext.login import login_user, logout_user

from evecomments.user.models import UserModel
from evecomments.extensions  import oauth, db, login_manager

blueprint = Blueprint('user', __name__, static_folder='../static')
evesso    = oauth.remote_app('evesso', app_key='EVESSO')


@blueprint.route("/login")
def login():
    return evesso.authorize(callback=url_for('user.authorized', _external=True))


@blueprint.route('/logout')
def logout():
    logout_user()

    return redirect(url_for('public.home'))


@blueprint.route('/callback')
def authorized():
    resp = evesso.authorized_response()

    if resp is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )

    if isinstance(resp, Exception):
        return 'Access denied: error=%s' % str(resp)

    session['evesso_token'] = (resp['access_token'], '')
    verify                  = evesso.get('verify')

    user = UserModel.query.filter_by(id=verify.data['CharacterID']).first()

    if user is None:
        user = UserModel(verify.data['CharacterID'], verify.data['CharacterName'], verify.data['CharacterOwnerHash'])
        user.login_count = 0
        user.join_date   = datetime.now()

    user.login_count += 1

    db.session.add(user)
    db.session.commit()

    login_user(user)

    return render_template('user/callback.html')


@evesso.tokengetter
def get_evesso_oauth_token():
    return session.get('evesso_token')


@login_manager.user_loader
def load_user(character_id):
    """ Required callback for Flask-Login. Returns the user DB object or None. """

    user = UserModel.query.filter_by(id=character_id).first()

    return user

evecomments/templates/base.html
{% import "macros.html" as macros %}

{% autoescape true %}
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <title>{% block title %}{% endblock %}</title>
            <link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap/dist/css/bootstrap.min.css') }}">

            <script src="{{ url_for('static', filename='vendor/jquery/dist/jquery.min.js') }}"></script>
            <script src="{{ url_for('static', filename='vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>

            <script src="{{ url_for('static', filename='js/evecomments.js') }}"></script>

            {% block head %}{% endblock %}
        </head>
        <body>
            <div class="container">
                {% block body %}{% endblock %}
            </div>
        </body>
    </html>
{% endautoescape %}

evecomments/templates/base_with_nav.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/evecomments.css') }}">
{% endblock %}

{% block body %}
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('public.home') }}">EVE Comments</a>
            </div>

            <a href="{{ url_for('sites.all_sites') }}">Sites</a>

            {% if current_user and current_user.is_authenticated() %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="navbar-link" href=""><img src="{{ current_user.get_image_server_link(32) }}"  class="img-rounded" /></a>
                    </li>
                    <li>
                        <p class="navbar-text">
                            <a class="navbar-link" href="">Logged in as {{ current_user.name }}</a>
                        </p>
                    </li>
                    <li>
                        <a class="navbar-link" href="{{ url_for('user.logout') }}">Logout</a>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('user.login') }}" class="ssoLogin" data-popup='width=560, height=560'>
                            <img src="{{ url_for('static', filename='img/eve_sso_white_small.png') }}" />
                        </a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>
    {% block content %}{% endblock %}
{% endblock %}

evecomments/templates/macros.html
{% macro add_comment(comment) %}
    <div class="row comment-row">
        <div class="pull-left">
            <img src="{{ comment.author.get_image_server_link(64) }}" class="img-rounded" />
        </div>
        <div class="comment-content">
            <div class="comment-header">
                {{ comment.author.name }} | {{ comment.created_on }}
            </div>
            <div class="comment-body">
                <pre>{{ comment.message }}</pre>
            </div>
            <div class="comment-footer">
                Some stuff for a footer here
            </div>
        </div>
    </div>
{% endmacro %}